-- AlterTable
ALTER TABLE "MoodboardItem" ALTER COLUMN "productId" DROP NOT NULL,
ADD COLUMN     "x" DOUBLE PRECISION NOT NULL DEFAULT 24,
ADD COLUMN     "y" DOUBLE PRECISION NOT NULL DEFAULT 24,
ADD COLUMN     "width" DOUBLE PRECISION NOT NULL DEFAULT 180,
ADD COLUMN     "kind" TEXT NOT NULL DEFAULT 'product',
ADD COLUMN     "label" TEXT,
ADD COLUMN     "colorHex" TEXT,
ADD COLUMN     "swatchImageUrl" TEXT;
