import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Sem <Nav/> aqui de propósito -- esta é a raiz de TODA rota, inclusive
// /present/[token] (link de apresentação, aberto por um cliente sem
// login e sem nenhuma razão pra ver "Clientes | Pipeline | Tarifas..."
// da equipe). Nav mora em (dashboard)/layout.tsx, só nas rotas
// autenticadas.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
