import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Era "Create Next App"/"Generated by create next app" -- o placeholder do
// scaffold nunca tinha sido trocado, e aparecia na aba do navegador de
// todo mundo. Inclusive em /present/[token], o link de apresentação que
// vai pro CLIENTE: a única tela que gente de fora vê, anunciando um app
// de exemplo do Next.
export const metadata: Metadata = {
  title: {
    default: "Araci — Studio Araci",
    // Cada página que definir `title` própria entra aqui, mantendo o
    // nome do estúdio no fim da aba.
    template: "%s · Araci",
  },
  description: "CRM, ERP e FF&E do Studio Araci.",
  applicationName: "Araci",
};

// Sem <Nav/> aqui de propósito -- esta é a raiz de TODA rota, inclusive
// /present/[token] (link de apresentação, aberto por um cliente sem
// login e sem nenhuma razão pra ver "Clientes | Pipeline | Tarifas..."
// da equipe). Nav mora em (dashboard)/layout.tsx, só nas rotas
// autenticadas.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
