import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Era "Create Next App"/"Generated by create next app" -- o placeholder do
// scaffold nunca tinha sido trocado, e aparecia na aba do navegador de
// todo mundo. Inclusive em /present/[token], o link de apresentação que
// vai pro CLIENTE: a única tela que gente de fora vê, anunciando um app
// de exemplo do Next.
export const metadata: Metadata = {
  title: {
    default: "Araci — Studio Araci",
    // Cada página que definir `title` própria entra aqui, mantendo o
    // nome do estúdio no fim da aba.
    template: "%s · Araci",
  },
  description: "CRM, ERP e FF&E do Studio Araci.",
  applicationName: "Araci",
};

// Sem <Nav/> aqui de propósito -- esta é a raiz de TODA rota, inclusive
// /present/[token] (link de apresentação, aberto por um cliente sem
// login e sem nenhuma razão pra ver "Clientes | Pipeline | Tarifas..."
// da equipe). Nav mora em (dashboard)/layout.tsx, só nas rotas
// autenticadas.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Auto-hospeda as fontes do Excalidraw (ver public/fonts,
            scripts/copy-excalidraw-fonts.mjs) em vez do fallback padrão
            da lib em esm.sh -- ver plano de migração tldraw->Excalidraw
            §6.4/§6.5. Forma literal, NUNCA NEXT_PUBLIC_*: uma env var
            nova exigiria entrada em render.yaml + ARG no Dockerfile +
            turbo.json tasks.build.env nos três (check-deploy-config.mjs
            é gate de CI), e turbo 2.x com envMode strict filtraria uma
            var esquecida em qualquer um dos três pra undefined
            silencioso. strategy padrão (afterInteractive), não
            beforeInteractive: o Excalidraw só é alcançado via
            next/dynamic ssr:false (ver excalidraw-canvas.tsx), ou seja,
            bem depois da hidratação de qualquer jeito -- e
            beforeInteractive real (achado testando num navegador de
            verdade) empurra um <script> pra dentro da árvore React de
            um jeito que colide com o hoisting nativo de <script> do
            React 19, gerando um warning de "script tag" a cada render. */}
        <Script id="excalidraw-asset-path">{`window.EXCALIDRAW_ASSET_PATH="/"`}</Script>
        {children}
      </body>
    </html>
  );
}
